### ISSUE TITLE
addChannelMessage(Id chan) cannot be overloaded

### ISSUE THREAD

**Issue by dharmasam9** [BhallaLab/moose#1]
```
> git clone https://github.com/BhallaLab/moose.git
> cd moose
> mkdir _build
> cd _build
> cmake ..
> make
```

[ 23%] Building CXX object biophysics/CMakeFiles/biophysics.dir/Neuron.cpp.o
cd /home/teja/Desktop/MOOSE/moose/_build/biophysics && /usr/bin/c++   -DARGS_CHECK -DQUIET_MODE -DRESULT_CHECK -DSANITY_CHECK -DUSE_GENESIS_PARSER -DUSE_GSL -DUSE_SBML -DVALUE_CHECK -std=c++11 -O3 -DNDEBUG -I/usr/local/include -I/home/teja/Desktop/MOOSE/moose/msg -I/home/teja/Desktop/MOOSE/moose/basecode -I/home/teja/Desktop/MOOSE/moose/biophysics/../basecode -I/home/teja/Desktop/MOOSE/moose/biophysics/../synapse -I/home/teja/Desktop/MOOSE/moose/biophysics/../utility    -Wall -Wno-unused-variable -Wno-unused-function -fPIC -UDO_UNIT_TESTS -O2 -DCYMOOSE -DCYTHON -o CMakeFiles/biophysics.dir/Neuron.cpp.o -c /home/teja/Desktop/MOOSE/moose/biophysics/Neuron.cpp
In file included from /home/teja/Desktop/MOOSE/moose/biophysics/Neuron.cpp:13:0:
/home/teja/Desktop/MOOSE/moose/biophysics/ReadCell.h:99:8: error: ‘void ReadCell::addChannelMessage(Id)’ cannot be overloaded
   void addChannelMessage( Id chan );
        ^
/home/teja/Desktop/MOOSE/moose/biophysics/ReadCell.h:35:15: error: with ‘static void ReadCell::addChannelMessage(Id)’
   static void addChannelMessage( Id chan );
               ^
make[2]: *** [biophysics/CMakeFiles/biophysics.dir/Neuron.cpp.o] Error 1
make[2]: Leaving directory `/home/teja/Desktop/MOOSE/moose/_build'
make[1]: *** [biophysics/CMakeFiles/biophysics.dir/all] Error 2
make[1]: Leaving directory `/home/teja/Desktop/MOOSE/moose/_build'
make: *** [all] Error 2

Source of the problem is In ReadCell.h same method is declared twice, once as static and normal.
* static void addChannelMessage( Id chan );
* void addChannelMessage( Id chan );

**Comment by dilawar** [comment]
Fixed.

**Comment by dharmasam9** [comment]
I did not pull changes from upstream. My bad.
