### ISSUE TITLE
Source and destination fields on messages cannot be accessed

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose#101]
Attempt to access fields on Msg objects result in segmentation fault in release build. In debug build, for some messages accessing src or dest fields result in error messages.
Sample code:
import moose

comp = moose.Compartment\('/comp'\)
chan = moose.HHChannel\('/comp/chan'\)
moose.connect\(comp, 'channel', chan, 'channel'\)

for m in comp.msgIn:
	print 'In Message:', m
print 'e1', m.getField\('e1'\)
print 'e2', m.getField\('e2'\)
print 'src-on-e2:', m.getField\('srcFieldsOnE2'\)
print 'dest-on-e1', m.getField\('destFieldsOnE1'\)
print 'src-on-e1:', m.getField\('srcFieldsOnE1'\)
print 'dest-on-e2', m.getField\('destFieldsOnE2'\)

for m in comp.msgOut:
print 'Out Message:', m
print 'e1', m.getField\('e1'\)
print 'e2', m.getField\('e2'\)
print 'src-on-e1:', m.getField\('srcFieldsOnE1'\)
print 'dest-on-e2', m.getField\('destFieldsOnE2'\)
print 'src-on-e2:', m.getField\('srcFieldsOnE2'\)
print 'dest-on-e1', m.getField\('destFieldsOnE1'\)
for m in comp.msgIn:
msg = moose.element\(m\)
print msg.e1 \# segmentation fault

Output:
In Message: &lt;ObjId: id=7, dataId=1412, path=/Msgs/oneToAllMsg\[1412\]&gt;
e1 /
e2 /comp
src-on-e2: \(\)
dest-on-e1 \(\)
src-on-e1:Error: Cinfo::srcFinfoName\( 0 \): not found
Error: Msg::getSrcFieldsOnE1: Failed to find field on msg root--&gt;comp
\(\)
dest-on-e2Error: Cinfo::destFinfoName\( 0 \): not found
Error: Msg::getDestFieldsOnE2: Failed to find field on msg root--&gt;comp
\(\)
Out Message: &lt;ObjId: id=7, dataId=1416, path=/Msgs/oneToAllMsg\[1416\]&gt;
e1 /comp
e2 /comp/chan
src-on-e1:Error: Cinfo::srcFinfoName\( 0 \): not found
Error: Msg::getSrcFieldsOnE1: Failed to find field on msg comp--&gt;chan
\(\)
dest-on-e2Error: Cinfo::destFinfoName\( 0 \): not found
Error: Msg::getDestFieldsOnE2: Failed to find field on msg comp--&gt;chan
\(\)
src-on-e2: \(\)
dest-on-e1 \(\)
Out Message: &lt;ObjId: id=5, dataId=1417, path=/Msgs/singleMsg\[1417\]&gt;
e1 /comp
e2 /comp/chan
src-on-e1: \('VmOut',\)
dest-on-e2Error: Cinfo::destFinfoName\( 20 \): not found
Error: Msg::getDestFieldsOnE2: Failed to find field on msg comp--&gt;chan
\(\)
src-on-e2:Error: Cinfo::srcFinfoName\( 1 \): not found
Error: Msg::getSrcFieldsOnE2: Failed to find field on msg comp--&gt;chan
\(\)
dest-on-e1 \('handleChannel',\)
Segmentation fault

Reported by: subhacom

**Comment by dilawar** [comment]
This example is working fine. Seems like it is fixed.
