### ISSUE TITLE
HHChannel Vm_ not updated from Compartment on reinit

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose#103]
When systemwide reinit\(\) is called, reinit\(\) method of Compartment sends out the Vm \(=initVm\). But although HHChannel is supposed to receive that value, HHChannel.handleVm is not called and Vm\_ = 0 is used in HHChannel.reinit\(\) resulting in errorneous initial values of m and h state variables. This might actually be a more general bug if messages are not synchronized  when sent at reinit\(\) call.

How to reproduce: Create a simple compartment with an  HHChannel, set initVm to something other than 0 and put a breakpoint at the reinit method of HHChannel. When the debugger breaks execution here, print Vm\_ and it will be 0.

Workaround: As a hack, one can explicitly set the initial values of X and Y state variables by interpolating from the gate tables.

Reported by: subhacom

**Comment by dilawar** [comment]
A very old ticket from sourceforge. Most likely to be fixed.
