### ISSUE TITLE
assertion failure if trying to schedule nonexistent object

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose#109]
The debug build aborts when the user tries to schedule a nonexistent path by mistake:

moose.useClock\(0, '/data/soma\_Vm', 'process'\)

gives:

Warning: no Elements found on path /data/soma\_Vm
python: Clock.cpp:765: void Clock::reinitPhase2\(ProcInfo\*\): Assertion \`currTickPtr\_ &lt; tickPtr\_.size\(\)' failed.

Reported by: subhacom

**Comment by dilawar** [comment]
Probably irrelevant now. Open it again otherwise on `moose-core`.
