### ISSUE TITLE
When using prototype from /library MOOSE crashes at exit

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose#117]
This happens after running a single compartment with prototype channels copied from library. Something funny happens with HHChannel destructor. Here is the gdb backtrace:

    Program received signal SIGSEGV, Segmentation fault.
    0x00007fffebec0a14 in Element::dataHandler (this=0x0) at Element.cpp:242
    242		return dataHandler_;
    (gdb) bt
    #0  0x00007fffebec0a14 in Element::dataHandler (this=0x0) at Element.cpp:242
    #1  0x00007fffebed3f57 in ObjId::data (this=0x7fffffffdfe0) at ObjId.cpp:66
    #2  0x00007fffebad03ad in HHChannel::~HHChannel (this=0x2583cb8, __in_chrg=<optimized out>) at HHChannel.cpp:212
    #3  0x00007fffebb3580e in Dinfo<HHChannel>::destroyData (this=0x1f4ac00, d=0x2583cb8 "\365\240\060\070\313鱿,\rC\210=v\314>\nףp=\n\247?*\215j3\226\234\364=\263q\371\021Y\365\302=") at ../basecode/Dinfo.h:132
    #4  0x00007fffebec66b7 in ZeroDimHandler::~ZeroDimHandler (this=0x248e520, __in_chrg=<optimized out>) at ZeroDimHandler.cpp:63
    #5  0x00007fffebec673a in ZeroDimHandler::~ZeroDimHandler (this=0x248e520, __in_chrg=<optimized out>) at ZeroDimHandler.cpp:65
    #6  0x00007fffebec02eb in Element::~Element (this=0x2367b40, __in_chrg=<optimized out>) at Element.cpp:116
    #7  0x00007fffebed394a in Id::destroy (this=0x277ba28) at Id.cpp:153
    #8  0x00007fffebec1e0a in Element::destroyElementTree (tree=...) at Element.cpp:495
    #9  0x00007fffeba651de in Neutral::destroy (this=0x1ffcc78, e=..., q=0x0, stage=0) at Neutral.cpp:493
    #10 0x00007fffebe0922a in finalize () at moosemodule.cpp:446
    #11 finalize () at moosemodule.cpp:405
    #12 0x00000000004af14b in Py_Finalize ()
    #13 0x00000000004aa72e in Py_Main ()
    #14 0x00007ffff68df76d in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
    #15 0x000000000041b9b1 in _start ()

How to reproduce: 
run this script <https://sourceforge.net/p/moose/code/HEAD/tree/moose/branches/buildQ/Demos/snippets/hhcomp.py> and at exit you get a sigsegv.

Reported by: subhacom

**Comment by dilawar** [comment]
Snippet is working fine on today's MOOSE.
