### ISSUE TITLE
PrepackedBuffer numEntries not populated for vector

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose#121]
According to code documentation, the "numEntries()" function in PrepackedBuffer should return the number of entries if an array is stored in the buffer. 

However, when a vector data field (e.g. Table.vec) is obtained using this, numEntries is always 0, the actual length of the vector is in PrepackedBuffer.data()[0] and actual data content starts at PrepackedBuffer.data()[1].
In otherwords, if we look at the data_ array in prepacked buffer:
    data_[0] = dataSize (total length)
    data_[1] = 0 - this seems always 0
    data_[2] = vector size
    data_[3 ... dataSize-1] - vector content

Reported by: *anonymous

**Comment by dilawar** [comment]
I can't say if this is  fixed @subhacom

**Comment by dilawar** [comment]
Closing it. Too old and no updates on it.
