### ISSUE TITLE
clock.currentTime inconsistent on slowest clock tick

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose#122]
When currentTime is recorded in a table where there are ticks at different time scales (dt), the recorded time lags by one step (dt) of the slowest tick at time points corresponding to the tick of the slowest clock-tick.

How to reproduce: the attached script produces a minimal example. The currentTime time is recorded in two tables, t1 at dt=0.1 and t2 at dt=10.0. These are saved in times1.txt and times2.txt respectively. The entry after 9.9 is 0.0 in stead of 10.0 in times1.txt, but the next one is correct: 10.1. After 19.8, it is 10.0 followed by 20.0 and and after 29.8 it is 20.0 followed by 30.0.

Reported by: subhacom

**Comment by dilawar** [comment]
Irrelevant now.
