### ISSUE TITLE
Problem finding compartments in SbmlReader.cpp

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose#143]
Following lines in `sbml/SbmlReader.cpp` return EMPTY vector of ChemCompts since base_.path() is already a compartment and ChemCompts MAY NOT exist as its children. 

~~~

+            string simpath = base_.path() + "/"+comptName+"/##[]";
+            wildcardFind( comptpath, compts );
~~~

Currently I am working without prefixing `base_.path()` to wildcard expression. One can also pop the very last expression from base_.path() before prefixing. 

 

Reported by: dilawar

**Comment by dilawar** [comment]
Moved to `moose-core`
