### ISSUE TITLE
Update Time Algorithm

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose#149]
Default update time algorithm: 

+ Read initial runtime from the following sources 
     * kkit file
     * annotations
     * runtime dialog
     * default to 100 second
+ plotdt = runtime / 100 unless file specifies otherwise.
+ simulationdt = plotdt. Ignore file if it is a kkit file.
+ guiupdate time = 
    1. runtime / 20. Run for 25% of runtime, ie, 5 updates.
    2. After 25% of runtime, Set update time = runtime / 10. 
    3. Run for remainder of runtime

Reported by: *anonymous

**Comment by dilawar** [comment]
Seems like this is a very old ticket related to GUI. @hrani Can it be closed/updated?

**Comment by dilawar** [comment]
Closing it. If it is valid, reopen it on moose-gui repo.
