### ISSUE TITLE
DifShell and DifBuffer compatibility

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose#157]
DifShells seem to be missing DifBuffers. To simulate calcium dynamics properly,
DifBuffers are required. Commits which added DifShell did not add that part.
Calcium Pump objects are also missing.
- Submitted by Zbigniew Jędrzejewski-Szmek

Reported by: subhacom

**Comment by dilawar** [comment]
Probably fixed long time ago. Did not keep track of it.

**Comment by subhacom** [comment]
Please confirm with upi. There was discussion over this in moose mailing list and according to him rdesigneur was to provide a better solution. Therefore diffbuffer implementation was not pushed much.

**Comment by dilawar** [comment]
@upibhalla

**Comment by dilawar** [comment]
PR https://github.com/BhallaLab/moose/pull/205 Implements it.

**Comment by dilawar** [comment]
Transferring this issue to BhallaLab/moose-core repo.
