### ISSUE TITLE
Standard location of moose data after installation 

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose#171]
DEBIAN and RPM packaging requires that configuration data should go to either `$HOME/.config` or /etc. 

Moreover, `Demos` should be stored at `/usr/share/moose`. 

These are the guidelines I've been following in CMake and upstream packages. Command `make install` may be made compatible with this to honour the policy.

Reported by: dilawar

**Comment by dilawar** [comment]
Fixed. `make install` uses `/usr/local` by default. Or as given by user during build `-DCMAKE_INSTALL_PREFIX=/path/to/install`.
