### ISSUE TITLE
Links to ppa and open build service should be updated.

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose#174]
The link to INSTALL file on [MOOSE web](http://moose.ncbs.res.in/content/view/35/70/) is very old and points to my PPA which is now replaced by [bhallalab/moose](https://launchpad.net/~bhallalab/+archive/ubuntu/moose). 

Also Open Build Service has [new page for MOOSE packages](http://software.opensuse.org/download.html?project=home%3Amoose&package=moose).

**Comment by hrani** [comment]
corrected
