### ISSUE TITLE
getId() of mooseObj should be exposed in python level

### ISSUE THREAD

**Issue by hrani** [BhallaLab/moose#175]
import moose
t = moose.Neutral('/test')
t.getId()
returns vector of the object instead Id of the moose object
<moose.vec: class=Neutral, id=458, path=/test>

This is useful to get at python level.
while writing to SBML I have issue as mooseObject with same name might exist with different compartment.
If I get Id of the object as number, then appending this along with name would be easy

**Comment by subhacom** [comment]
By vector you mean `moose.vec`? That is just a wrapper over Id. To see if two objects with same name are actually different you can just compare the vecs. Also, instead of calling getId() function, you could simply write `t.vec`. If you want the numeric value, use `t.vec.value`.

**Comment by hrani** [comment]
Thank you Subha. I needed value.
