### ISSUE TITLE
Mac os support

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose#177]
It should not be hard to provide mac os support in moose build system as this is a unix clone. mac support was implemented in 2008 but was not maintained. With fewer dependencies it should be even simpler now.

**Comment by dilawar** [comment]
Default Xcode toolchain, discourage static libraries. Module _moose.so, wont work unless all components are statically linked due to `static` Cinfo. [see]9https://isocpp.org/wiki/faq/ctors#static-init-order).

Will test with `gnu` linker. Not sure what implication it might have on the package: the c runtime environment has to be shipped with package I guess.

**Comment by dilawar** [comment]
`gcc` toolchain installed with `brew` having linking issues. Cmake is linking with static stdc++ which should work. Problem with architecture symbol support. Known issue with brew. Testing with `macports` now which has better gcc support. 

Clang linker does not support static linking with `--whole-archive`. The `-static` option complains about missing `libctrl.o` file. If nothing works, manually compile the missing `libcrt0.o` file.

**Comment by dilawar** [comment]
Build and test successful with default Xcode toolchain on MAC. `--whole-archive` option needed to be replaced by `-load_all` and `-noload_all` option. Packaging now should be straightforward from now on. 

Currently implemented on `macos` branch in fork https://github.com/dilawar/moose-core.

**Comment by dilawar** [comment]
Submitted brew script:

https://github.com/Homebrew/homebrew-science/pull/2958

**Comment by dilawar** [comment]
Brew script passes all tests. Waiting for it to get merged with official repository. Next is MacPort.

**Comment by dilawar** [comment]
MacPort also passes without any issues. Submitted port https://trac.macports.org/ticket/49557

**Comment by dilawar** [comment]
Instead of using `moose-full` in moose brew formulae, use `moose-core` and `moose-gui` repositories along with `moose-example`. This will audit problems of `GitHub repository not notable enough (<10 forks, <10 watchers and <20 stars)`.

**Comment by dilawar** [comment]
A 88MB dmg file is released today. Tested on three versions of mac : 10.11, 10.9 and 10.8. Works fine. `moose-gui` canvas for creating new models does not work. That has been reported on moose-gui repository.

**Comment by dilawar** [comment]
A bugfix release.

**Comment by dilawar** [comment]
The 3.1.0 version is already in homebrew/science taps.. This should now be closed.
