### ISSUE TITLE
Problem opening moose-gui on Ubuntu 15.10

### ISSUE THREAD

**Issue by MelanieIStefan** [BhallaLab/moose#186]
I have installed moose-python and moose-gui on Ubuntu 15.10 using the PPA. Moose-python seems to work, but on running moosegui I get the following error message: 

``` 
/usr/bin/moosegui: line 2: syntax error near unexpected token `)'
/usr/bin/moosegui: line 2: `cd /usr/lib/moose/gui && python mgui.py )'
```

**Comment by dilawar** [comment]
Tested moose packages are available here:

https://software.opensuse.org/download.html?project=home%3Amoose&package=moose

I'll fix the launchpad ppa as well. It's embarrassing that it didn't work.

**Comment by MelanieIStefan** [comment]
When trying to install moose following the instructions there, I run into a different problem: 

```
The following packages have unmet dependencies:
 moose : Depends: libhdf5-7 but it is not installable or
                  libhdf5-serial-1.8.4 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

The current version of libhdf seems to be 5-10. Should I try to downgrade to libhdf5-7, or is there something else I can/should do?

Thanks! It's not at all embarrasing by the way! With any piece of software, there will be things that work and things that don't at first. You're doing a great job :)

**Comment by dilawar** [comment]
I've triggered a fresh rebuild with modified dependencies (libhdf5 is now statically linked). The new package should be available in 10 minutes or so. I'll test it and PPA on Virtualbox and update you.

**Comment by dilawar** [comment]
Fixed and tested on virtual-box - Ubuntu 15.10. Get the latest package on https://software.opensuse.org/download.html?project=home%3Amoose&package=moose . 

       $ sudo apt-get update
       $ sudo apt-get install moose moogli

Some demos required 3-d visualizer (beta release) moogli.

**Comment by MelanieIStefan** [comment]
All working now! Thanks!

**Comment by dilawar** [comment]
PPA is fixed too. The moose-gui should launch with command `moosegui` . The packages might take some time to get updated on PPA. I am closing the issue.
