### ISSUE TITLE
Moose 3.02 in Mac "Cannot access /usr/share/doc/moose"

### ISSUE THREAD

**Issue by YubinXie** [BhallaLab/moose#187]
Hi
When I open moosegui in Mac OS 10.11, this error comes out.

[INFO] PYTHONPATH aleady contains /Volumes/Moose_3.0.2/lib/python2.7/site-packages
Could not access Demos directory: /usr/share/doc/moose
[Errno 13] Cannot access /usr/share/doc/moose

I used sudo chown -R but it could not change the permission. Is this a big problem?

**Comment by dilawar** [comment]
This is not a serious issue for python scripting or running demos. However, we have some issues with `matplotlib` with moose-gui on MacOSX. You can still use python interface and run demos without much problem, but would not be able to create the chemical models in GUI. This is most likely to be resolved soon as soon as we replace the compatible icons and make the GUI look consistent. 

Our Linux releases (https://github.com/BhallaLab/moose/wiki/Install) have working gui (beta).

**Comment by hrani** [comment]
Hi,
I have resolved this issue on MacOSX, now we can use the GUI for running
and creating Chemical model.But it may not be available immediately unless
beta release.
I would suggest you could clone just moose-gui from the repository and run
the same.
Let us know you if you need any help.

Harsha

**Comment by hrani** [comment]
@YubinXie : It's supposed to be a "warning" rather than "error" , this will be removed.

@dilawar : There is no issues with matplotlib with moose-gui on MacOSX, this is tested

The toolbar was not displaying and that is fixed  in
https://github.com/BhallaLab/moose-gui/commit/0a8afe174005b618cfaf4ec5204a49d62904b752

**Comment by YubinXie** [comment]
Got it. Thanks!
