### ISSUE TITLE
Testing of one-click install packages 

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose#188]
TODO list for developer to test  the packages after building them.
## moose-python (server version, just moose-python)

Location: https://build.opensuse.org/package/show/home:moose/moose-python
- [x] CentOS_6,  _Virutualbox, CentOS-6.7, Passed_
- [x] CentOS_7
- [x] Debian_7.0
- [ ] Debian_8.0  
## moose (moose+gui+moogli)

To download: 

```
   $  osc getbinaries home:dilawar/moose/Fedora_22/x86_64
   $ osc getbinaries home:dilawar/moose/Debian_8.0/i586 
      etc.. 
```
- [x] Ubuntu, 12.04
- [x] Ubuntu, 14.04, _Virtualbox, Passed._ 
- [x] CentOS -7, Users need to do some fixes, see the comment below. 
- [x] Fedora_22, _Installs fine but gui does not launch. See the comment below_
- [x] openSUSE_13.2, _Installs fine but gui does not launch. See the comment below_

**Comment by dilawar** [comment]
On Fedora run-time requirement `python-numpy` has to be changed to `numpy`. Fixed and rebuilding now.

**Comment by dilawar** [comment]
Debian-8.0 packages do not install on Ubuntu-14.04. xUbuntu-14.04 package installs and runs fine. We need to distribute Debian packages along with Ubuntu (at least the server).

**Comment by dilawar** [comment]
Fedora, openSUSE installation is fine but issue https://github.com/BhallaLab/moose-gui/issues/4 is not fixed yet.

**Comment by hrani** [comment]
One-Click package did not install, On "Ubuntu 14.04.3 LTS", getting package from 
/pantua-data/Packages/xUbuntu_14.04/binaries/moose_3.0.2_amd64.deb
And running sudo dpkg --install moose_3.0.2_amd64.deb

dependency problems prevent configuration of moose:
 moose depends on python-numpy-abi9, python-numpy,python-nose,python-networkx, python-matplotlib,python-suds,python-qt4-gl,libqt4-gui ; however:  Package is not installed.

dpkg: error processing package moose (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:

Harsha
 moose

**Comment by dilawar** [comment]
Did it work with software center? With dpkg, you have to install the dependencies using `apt`.

**Comment by dilawar** [comment]
Probably `sudo apt-get install -f` will also fix it automatically.

**Comment by hrani** [comment]
On Ubunut 14.04, 64 machine 

A. sudo dpkg --install moose_3.0.2_amd64.deb doesn't install the package
B. Same with software center
Before this one need to run ``sudo apt-get install -f``

**Comment by hrani** [comment]
Centos 7
I)
A. sudo -E rpm -ivh moose-3.0.2-10.1.x86_64.rpm
warning: moose-3.0.2-10.1.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID c63fed39: NOKEY
error: Failed dependencies:
PyQt4 is needed by moose-3.0.2-10.1.x86_64
numpy is needed by moose-3.0.2-10.1.x86_64
python-matplotlib is needed by moose-3.0.2-10.1.x86_64
python-networkx is needed by moose-3.0.2-10.1.x86_64

                                       or 
B. sudo -E yum install moose-3.0.2-10.1.x86_64.rpm

II. In the dependency package I don't see suds mentioning, so if user install the mentioned required packages, one some one tries to open the gui its says suds package missing and even after that it complaints for some package missing

**Comment by hrani** [comment]
On Mac 10.6.8, Installation is fine but some one try clicking on mooseGui icon or try running mooseGui its says
File "mgui.py", line 57, in 
from PyQt4 import QtGui, QtCore, Qt
ImportError:
dlopen(/Volumes/Moose_3.0.2/lib/python2.7/site-packages/PyQt4/QtGui.so,
2): Symbol not found: _OBJC_CLASS_$_NSUserNotification
Referenced from:
/Volumes/Moose_3.0.2/opt/qt/lib/QtGui.framework/Versions/4/QtGui
Expected in:
/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

**Comment by dilawar** [comment]
On cenos-7.

- Dependency python-networkx is not in default repo. User has to enable epel before conitnuing.
      $ sudo yum install epel-release 
- After than user can install rpm.

Post installation fixes:
  
- Install `python-matolotlib-qt4` to be able to get proper qt4 backed. This can be put in centos-7 dependencies (not sure whether that would  break the centos-6 built).
- Install `python-suds`. This is really not needed if this is resolved https://github.com/BhallaLab/moose-gui/pull/9 

Upstream version of `python-suds` are not maintained. Newer version is known not to work.

**Comment by championswimmer** [comment]
On version 3.1.0, the debian/control file does not have python-suds as dependencies

The debian/control of v3.1.0 (as available on Open Build System) is - 
```
Package: moose
Version: 3.1.0
Architecture: amd64
Maintainer: Dilawar Singh <dilawars@ncbs.res.in>
Installed-Size: 38359
Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libpython2.7 (>= 2.7), libstdc++6 (>= 5.2), libxml2 (>= 2.7.4), python (>= 2.7), python (<< 2.8), python-numpy-abi9, python-lxml, python-numpy, python-matplotlib, python-nose, python-networkx, python-qt4
Section: science
Priority: optional
Homepage: http://moose.ncbs.res.in
Description: the Multiscale Object-Oriented Simulation Environment
 It is the base and numerical core for large, detailed simulations including Computational Neuroscience and Systems Biology.
 .
 MOOSE spans the range from single molecules to subcellular networks, from
 single cells to neuronal networks, and to still larger systems.  MOOSE uses
 Python for scripting compatibility with a large range of software and
 analysis tools. It recognizes model definition standards including SBML,
 NeuroML, and GENESIS model file formatsGallery
 .
 MOOSE is open source software, licensed under the LGPL (Lesser GNU Public
 License). It has absolutely no warranty.
 .
 The MOOSE team is also participating in development of MOOGLI: a library and
 standalone application for displaying time-course of activity of detailed 3-D
 network models using OpenGL and also using OpenSceneGraph
```

Other than needing to manually `apt-get install python-suds`, this package works as a one-click install on (Lu/Xu/U)buntu 16.04 and 16.10

**Comment by dilawar** [comment]
New release it out. This is now redundant. 

CentOS-6 is deprecated on Open Build Service.
