### ISSUE TITLE
How to run NEURON channel file mod format into moose? 

### ISSUE THREAD

**Issue by yubintse** [BhallaLab/moose#190]
How to run NEURON channel file mod format into moose? Or do you know how to convert Neuron channel file mod into ChannelML format?
Thanks!

**Comment by dilawar** [comment]
MOOSE does not read MOD file. You can try to find equivalent channel file in NeuroML/ChannelML format (version 1.x) which MOOSE supports. Some of these channels are here https://github.com/BhallaLab/benchmarks/tree/master/moose_nrn_equivalence_testing/chans  . You can find others here https://neuroml-db.org/search_model

**Comment by yubintse** [comment]
Thanks for the suggestion. The channels that I need can not be found in the database of NeuroML and moose. I'll try to find some alternative ones or I can not convert mod file into NeuronML. Thanks!
