### ISSUE TITLE
readSBML core dumped

### ISSUE THREAD

**Issue by MelanieIStefan** [BhallaLab/moose#191]
I have used moose.readSBML successfully in the past, but now I get the following error message:

*** Error in `python': free(): invalid pointer: 0x00007ffff3b8d9e8 ***
Aborted (core dumped)

Running the latest version of moose and Python 2.7.10 on Ubuntu 15.10

Also I realise that the loadSbml.py snippet has gone from the snippets folder, so maybe this means you are working on this already.

**Comment by hrani** [comment]
This will be moved to moose-core from moose
