### ISSUE TITLE
Reading error of channel file in NeuroML format

### ISSUE THREAD

**Issue by yubintse** [BhallaLab/moose#192]
I want to import a NeuroML named KAHP_CML in chanProto of Rdesigneur. But it seems this file is special that it has six transition and in this case, the transition name can not be alpha and beta only. However, moose only recognise alpha and beta as transition name as I found in ChannelML.py file, line 243:     ## I assume that transitions if present are called alpha and beta
            ## for forward and backward transitions...
I really need this channel and I was wondering if there is any way can solve  this problem? Thanks! The link of the channel file is attached. https://neuroml-db.org/render_xml_file?modelID=NMLCH000091

**Comment by adityagilra** [comment]
Hi yubintse,

There are two parts to this issue. One is that the ChannelML.py accepts only alpha and beta as transition names. The second is (as far as I remember) that moose only supports two states open and closed per gate (max 3 gates in a channel), with the associated forward and backward rates (alpha and beta). So what needs to be done first is multi-state gate support in moose and only then the ChannelML.py file can be updated. Perhaps other moose developers may comment on multi-state support, if planned or present.

Best,
Aditya.

**Comment by pgleeson** [comment]
@yubintse just to clarify from the neuroConstruct point of view, ChannelML files like that could only be mapped to the kinetic scheme based Neuron mod files, whereas ChannelML files with one open, one closed state could be mapped to Neuron mod, Genesis or Moose format. 

There weren't many examples of ChannelML files with multiple open/closed states, so it's not too surprising that such forms aren't yet supported by Moose's native importer.

On a related note, the latest version of the channels from this model can be found here: https://github.com/OpenSourceBrain/SolinasEtAl-GolgiCell, and there is also a version of the model exported in NeuroML version 2:  https://github.com/OpenSourceBrain/SolinasEtAl-GolgiCell/tree/master/NeuroML2

**Comment by dilawar** [comment]
Open an enhancement request on moose-core.
