### ISSUE TITLE
"import moose" error post make

### ISSUE THREAD

**Issue by dharmasam9** [BhallaLab/moose#2]
After successfully building the source, I tried to import moose from python terminal. This gave me following error.

```
teja@teja:~/Desktop/MOOSE/moose/python$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import moose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "moose/__init__.py", line 29, in <module>
    from .moose import *
  File "moose/moose.py", line 43, in <module>
    from . import _moose
ImportError: moose/_moose.so: undefined symbol: BZ2_bzlibVersion
```

I have installed corresponding packages in ubuntu 
```
sudo apt-get install zlib1g zlib1g-dev
```

Can some one point out what might be the problem. 
Is there a wiki page containing list of ubuntu packages and python packages that needs to installed?

**Comment by dilawar** [comment]
I've been struggling to overcome this problem with latest bzip library which is used by SBML. If you are not using `sbml` with moose, I'd suggest to build moose without sbml support.

After pulling the upstream, 

cd _build
cmake -DENABLE_SBML=OFF ..
make

**Comment by dilawar** [comment]
SBML needs to be compiled with -lxml2 and -lbzip2 before installation. Download the libsbml-5.9.0:

~~~~
./configure --with-lxml2 --with-bz2
make 
sudo make install
~~~~

This should get rid of these linking issues.

**Comment by dilawar** [comment]
Closing the issue since there is no comment on it.
