### ISSUE TITLE
moose import error after manual installation

### ISSUE THREAD

**Issue by ChakrapaniNCBS** [BhallaLab/moose#216]
After compiling moose,trying to import moose from python and got the following error
 
```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import moose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/moose/__init__.py", line 25, in <module>
    from .moose import *
ImportError: No module named moose

```

**Comment by dilawar** [comment]
I tried on ubuntu-14.04. Seemed to work just fine. 

Following is the installation log for `moose-core` subdirectory:

```
sudo make install
[sudo] password for dilawars: 
[  3%] Built target intfire
[ 14%] Built target basecode
[ 18%] Built target muparser
[ 21%] Built target msg
[ 25%] Built target shell
[ 32%] Built target randnum
[ 32%] Built target scheduling
[ 50%] Built target biophysics
[ 59%] Built target moose_builtins
[ 62%] Built target utility
[ 67%] Built target mesh
[ 68%] Built target moose_mpi
[ 69%] Built target signeur
[ 77%] Built target ksolve
[ 83%] Built target hsolve
[ 85%] Built target diffusion
[ 86%] Built target device
[ 86%] Built target benchmarks
[ 92%] Built target kinetics
[ 96%] Built target synapse
[ 96%] Built target libmoose
[ 97%] Built target moose.bin
[ 98%] Copying required python files and other files to build directory
[ 98%] Built target copy_python_files
[100%] Built target _moose
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/moose.bin
-- Removed runtime path from "/usr/local/bin/moose.bin"
-- Installing: /usr/local/lib/libmoose.so
-- Removed runtime path from "/usr/local/lib/libmoose.so"
-- Installing: /usr/local/bin/moose
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/rdesigneur
copying rdesigneur/rdesigneur.py -> build/lib.linux-x86_64-2.7/rdesigneur
copying rdesigneur/rmoogli.py -> build/lib.linux-x86_64-2.7/rdesigneur
copying rdesigneur/__init__.py -> build/lib.linux-x86_64-2.7/rdesigneur
copying rdesigneur/rdesigneurProtos.py -> build/lib.linux-x86_64-2.7/rdesigneur
creating build/lib.linux-x86_64-2.7/moose
copying moose/hdfutil.py -> build/lib.linux-x86_64-2.7/moose
copying moose/recording.py -> build/lib.linux-x86_64-2.7/moose
copying moose/methods_utils.py -> build/lib.linux-x86_64-2.7/moose
copying moose/merge.py -> build/lib.linux-x86_64-2.7/moose
copying moose/graph_utils.py -> build/lib.linux-x86_64-2.7/moose
copying moose/print_utils.py -> build/lib.linux-x86_64-2.7/moose
copying moose/moose_constants.py -> build/lib.linux-x86_64-2.7/moose
copying moose/verification_utils.py -> build/lib.linux-x86_64-2.7/moose
copying moose/add_Delete_ChemicalSolver.py -> build/lib.linux-x86_64-2.7/moose
copying moose/constants.py -> build/lib.linux-x86_64-2.7/moose
copying moose/moose_config.py -> build/lib.linux-x86_64-2.7/moose
copying moose/graphutil.py -> build/lib.linux-x86_64-2.7/moose
copying moose/plot_utils.py -> build/lib.linux-x86_64-2.7/moose
copying moose/sim_utils.py -> build/lib.linux-x86_64-2.7/moose
copying moose/moose.py -> build/lib.linux-x86_64-2.7/moose
copying moose/__init__.py -> build/lib.linux-x86_64-2.7/moose
copying moose/alternate.py -> build/lib.linux-x86_64-2.7/moose
copying moose/optimizer_interface.py -> build/lib.linux-x86_64-2.7/moose
copying moose/utils.py -> build/lib.linux-x86_64-2.7/moose
creating build/lib.linux-x86_64-2.7/moose/SBML
copying moose/SBML/readSBML.py -> build/lib.linux-x86_64-2.7/moose/SBML
copying moose/SBML/validation.py -> build/lib.linux-x86_64-2.7/moose/SBML
copying moose/SBML/writeSBML.py -> build/lib.linux-x86_64-2.7/moose/SBML
copying moose/SBML/__init__.py -> build/lib.linux-x86_64-2.7/moose/SBML
creating build/lib.linux-x86_64-2.7/moose/neuroml
copying moose/neuroml/ChannelML.py -> build/lib.linux-x86_64-2.7/moose/neuroml
copying moose/neuroml/NeuroML.py -> build/lib.linux-x86_64-2.7/moose/neuroml
copying moose/neuroml/__init__.py -> build/lib.linux-x86_64-2.7/moose/neuroml
copying moose/neuroml/utils.py -> build/lib.linux-x86_64-2.7/moose/neuroml
copying moose/neuroml/MorphML.py -> build/lib.linux-x86_64-2.7/moose/neuroml
copying moose/neuroml/NetworkML.py -> build/lib.linux-x86_64-2.7/moose/neuroml
creating build/lib.linux-x86_64-2.7/moose/genesis
copying moose/genesis/writeKkit.py -> build/lib.linux-x86_64-2.7/moose/genesis
copying moose/genesis/__init__.py -> build/lib.linux-x86_64-2.7/moose/genesis
creating build/lib.linux-x86_64-2.7/moose/chemUtil
copying moose/chemUtil/chemConnectUtil.py -> build/lib.linux-x86_64-2.7/moose/chemUtil
copying moose/chemUtil/graphUtils.py -> build/lib.linux-x86_64-2.7/moose/chemUtil
copying moose/chemUtil/add_Delete_ChemicalSolver.py -> build/lib.linux-x86_64-2.7/moose/chemUtil
copying moose/chemUtil/__init__.py -> build/lib.linux-x86_64-2.7/moose/chemUtil
package init file 'moose/merge/__init__.py' not found (or not a regular file)
creating build/lib.linux-x86_64-2.7/moose/merge
copying moose/merge/mtypes.py -> build/lib.linux-x86_64-2.7/moose/merge
copying moose/merge/merge.py -> build/lib.linux-x86_64-2.7/moose/merge
copying moose/_moose.so -> build/lib.linux-x86_64-2.7/moose
package init file 'moose/merge/__init__.py' not found (or not a regular file)
running install_lib
creating /usr/local/lib/python2.7/dist-packages/rdesigneur
copying build/lib.linux-x86_64-2.7/rdesigneur/rdesigneur.py -> /usr/local/lib/python2.7/dist-packages/rdesigneur
copying build/lib.linux-x86_64-2.7/rdesigneur/rmoogli.py -> /usr/local/lib/python2.7/dist-packages/rdesigneur
copying build/lib.linux-x86_64-2.7/rdesigneur/__init__.py -> /usr/local/lib/python2.7/dist-packages/rdesigneur
copying build/lib.linux-x86_64-2.7/rdesigneur/rdesigneurProtos.py -> /usr/local/lib/python2.7/dist-packages/rdesigneur
creating /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/hdfutil.py -> /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/recording.py -> /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/methods_utils.py -> /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/merge.py -> /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/graph_utils.py -> /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/print_utils.py -> /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/_moose.so -> /usr/local/lib/python2.7/dist-packages/moose
creating /usr/local/lib/python2.7/dist-packages/moose/chemUtil
copying build/lib.linux-x86_64-2.7/moose/chemUtil/chemConnectUtil.py -> /usr/local/lib/python2.7/dist-packages/moose/chemUtil
copying build/lib.linux-x86_64-2.7/moose/chemUtil/graphUtils.py -> /usr/local/lib/python2.7/dist-packages/moose/chemUtil
copying build/lib.linux-x86_64-2.7/moose/chemUtil/add_Delete_ChemicalSolver.py -> /usr/local/lib/python2.7/dist-packages/moose/chemUtil
copying build/lib.linux-x86_64-2.7/moose/chemUtil/__init__.py -> /usr/local/lib/python2.7/dist-packages/moose/chemUtil
copying build/lib.linux-x86_64-2.7/moose/moose_constants.py -> /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/verification_utils.py -> /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/add_Delete_ChemicalSolver.py -> /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/constants.py -> /usr/local/lib/python2.7/dist-packages/moose
creating /usr/local/lib/python2.7/dist-packages/moose/genesis
copying build/lib.linux-x86_64-2.7/moose/genesis/writeKkit.py -> /usr/local/lib/python2.7/dist-packages/moose/genesis
copying build/lib.linux-x86_64-2.7/moose/genesis/__init__.py -> /usr/local/lib/python2.7/dist-packages/moose/genesis
creating /usr/local/lib/python2.7/dist-packages/moose/neuroml
copying build/lib.linux-x86_64-2.7/moose/neuroml/ChannelML.py -> /usr/local/lib/python2.7/dist-packages/moose/neuroml
copying build/lib.linux-x86_64-2.7/moose/neuroml/NeuroML.py -> /usr/local/lib/python2.7/dist-packages/moose/neuroml
copying build/lib.linux-x86_64-2.7/moose/neuroml/__init__.py -> /usr/local/lib/python2.7/dist-packages/moose/neuroml
copying build/lib.linux-x86_64-2.7/moose/neuroml/utils.py -> /usr/local/lib/python2.7/dist-packages/moose/neuroml
copying build/lib.linux-x86_64-2.7/moose/neuroml/MorphML.py -> /usr/local/lib/python2.7/dist-packages/moose/neuroml
copying build/lib.linux-x86_64-2.7/moose/neuroml/NetworkML.py -> /usr/local/lib/python2.7/dist-packages/moose/neuroml
copying build/lib.linux-x86_64-2.7/moose/moose_config.py -> /usr/local/lib/python2.7/dist-packages/moose
creating /usr/local/lib/python2.7/dist-packages/moose/merge
copying build/lib.linux-x86_64-2.7/moose/merge/mtypes.py -> /usr/local/lib/python2.7/dist-packages/moose/merge
copying build/lib.linux-x86_64-2.7/moose/merge/merge.py -> /usr/local/lib/python2.7/dist-packages/moose/merge
copying build/lib.linux-x86_64-2.7/moose/graphutil.py -> /usr/local/lib/python2.7/dist-packages/moose
creating /usr/local/lib/python2.7/dist-packages/moose/SBML
copying build/lib.linux-x86_64-2.7/moose/SBML/readSBML.py -> /usr/local/lib/python2.7/dist-packages/moose/SBML
copying build/lib.linux-x86_64-2.7/moose/SBML/validation.py -> /usr/local/lib/python2.7/dist-packages/moose/SBML
copying build/lib.linux-x86_64-2.7/moose/SBML/writeSBML.py -> /usr/local/lib/python2.7/dist-packages/moose/SBML
copying build/lib.linux-x86_64-2.7/moose/SBML/__init__.py -> /usr/local/lib/python2.7/dist-packages/moose/SBML
copying build/lib.linux-x86_64-2.7/moose/plot_utils.py -> /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/sim_utils.py -> /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/moose.py -> /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/__init__.py -> /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/alternate.py -> /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/optimizer_interface.py -> /usr/local/lib/python2.7/dist-packages/moose
copying build/lib.linux-x86_64-2.7/moose/utils.py -> /usr/local/lib/python2.7/dist-packages/moose
byte-compiling /usr/local/lib/python2.7/dist-packages/rdesigneur/rdesigneur.py to rdesigneur.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/rdesigneur/rmoogli.py to rmoogli.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/rdesigneur/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/rdesigneur/rdesigneurProtos.py to rdesigneurProtos.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/hdfutil.py to hdfutil.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/recording.py to recording.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/methods_utils.py to methods_utils.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/merge.py to merge.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/graph_utils.py to graph_utils.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/print_utils.py to print_utils.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/chemUtil/chemConnectUtil.py to chemConnectUtil.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/chemUtil/graphUtils.py to graphUtils.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/chemUtil/add_Delete_ChemicalSolver.py to add_Delete_ChemicalSolver.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/chemUtil/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/moose_constants.py to moose_constants.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/verification_utils.py to verification_utils.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/add_Delete_ChemicalSolver.py to add_Delete_ChemicalSolver.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/constants.py to constants.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/genesis/writeKkit.py to writeKkit.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/genesis/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/neuroml/ChannelML.py to ChannelML.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/neuroml/NeuroML.py to NeuroML.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/neuroml/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/neuroml/utils.py to utils.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/neuroml/MorphML.py to MorphML.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/neuroml/NetworkML.py to NetworkML.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/moose_config.py to moose_config.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/merge/mtypes.py to mtypes.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/merge/merge.py to merge.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/graphutil.py to graphutil.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/SBML/readSBML.py to readSBML.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/SBML/validation.py to validation.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/SBML/writeSBML.py to writeSBML.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/SBML/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/plot_utils.py to plot_utils.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/sim_utils.py to sim_utils.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/moose.py to moose.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/alternate.py to alternate.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/optimizer_interface.py to optimizer_interface.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/moose/utils.py to utils.pyc
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/moose-3.1.0_358_g07fc0f9-py2.7.egg-info
dilawars@ghevar ~/Work/GITHUB/BhallaLab/moose-core/_build (master) $
unset PYTHONPATH
dilawars@ghevar ~/Work/GITHUB/BhallaLab/moose-core/_build (master) $
python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
i>>> 
>>> import moose
>>> print moose.__file__
/usr/local/lib/python2.7/dist-packages/moose/__init__.pyc
```

I suspect that PYTHONPATH are messed up on this machine or python is not searching `/usr/local/lib/python2.7/dist-package` . 

I tried it on a fresh virtualbox machine as well. May be you can attach the full installation log.

**Comment by ChakrapaniNCBS** [comment]
Python looks fine, because other installed modules are importing well.
I have python version 2.7.12, Ubuntu 16.04.2 LTS" OS
I noticed that, during 'make'  there is some error while creating link to ../python/moose/_moose.so
Please find the make logs below

Scanning dependencies of target device
[ 81%] Building CXX object device/CMakeFiles/device.dir/PulseGen.cpp.o
[ 81%] Building CXX object device/CMakeFiles/device.dir/DiffAmp.cpp.o
[ 82%] Building CXX object device/CMakeFiles/device.dir/PIDController.cpp.o
[ 82%] Building CXX object device/CMakeFiles/device.dir/RC.cpp.o
[ 83%] Linking CXX static library libdevice.a
[ 83%] Built target device
Scanning dependencies of target benchmarks
[ 83%] Building CXX object benchmarks/CMakeFiles/benchmarks.dir/benchmarks.cpp.o
[ 84%] Building CXX object benchmarks/CMakeFiles/benchmarks.dir/kineticMarks.cpp.o
[ 84%] Linking CXX static library libbenchmarks.a
[ 84%] Built target benchmarks
Scanning dependencies of target kinetics
[ 84%] Building CXX object kinetics/CMakeFiles/kinetics.dir/PoolBase.cpp.o
[ 85%] Building CXX object kinetics/CMakeFiles/kinetics.dir/Pool.cpp.o
[ 85%] Building CXX object kinetics/CMakeFiles/kinetics.dir/BufPool.cpp.o
[ 85%] Building CXX object kinetics/CMakeFiles/kinetics.dir/ReacBase.cpp.o
[ 86%] Building CXX object kinetics/CMakeFiles/kinetics.dir/Reac.cpp.o
[ 86%] Building CXX object kinetics/CMakeFiles/kinetics.dir/EnzBase.cpp.o
[ 87%] Building CXX object kinetics/CMakeFiles/kinetics.dir/CplxEnzBase.cpp.o
[ 87%] Building CXX object kinetics/CMakeFiles/kinetics.dir/Enz.cpp.o
[ 87%] Building CXX object kinetics/CMakeFiles/kinetics.dir/MMenz.cpp.o
[ 88%] Building CXX object kinetics/CMakeFiles/kinetics.dir/Species.cpp.o
[ 88%] Building CXX object kinetics/CMakeFiles/kinetics.dir/ReadKkit.cpp.o
[ 89%] Building CXX object kinetics/CMakeFiles/kinetics.dir/WriteKkit.cpp.o
[ 89%] Building CXX object kinetics/CMakeFiles/kinetics.dir/ReadCspace.cpp.o
[ 90%] Building CXX object kinetics/CMakeFiles/kinetics.dir/lookupVolumeFromMesh.cpp.o
[ 90%] Building CXX object kinetics/CMakeFiles/kinetics.dir/testKinetics.cpp.o
[ 90%] Linking CXX static library libkinetics.a
[ 90%] Built target kinetics
Scanning dependencies of target synapse
[ 91%] Building CXX object synapse/CMakeFiles/synapse.dir/GraupnerBrunel2012CaPlasticitySynHandler.cpp.o
[ 91%] Building CXX object synapse/CMakeFiles/synapse.dir/SimpleSynHandler.cpp.o
[ 91%] Building CXX object synapse/CMakeFiles/synapse.dir/testSynapse.cpp.o
[ 92%] Building CXX object synapse/CMakeFiles/synapse.dir/SynHandlerBase.cpp.o
[ 92%] Building CXX object synapse/CMakeFiles/synapse.dir/RollingMatrix.cpp.o
[ 93%] Building CXX object synapse/CMakeFiles/synapse.dir/STDPSynHandler.cpp.o
[ 93%] Building CXX object synapse/CMakeFiles/synapse.dir/STDPSynapse.cpp.o
[ 93%] Building CXX object synapse/CMakeFiles/synapse.dir/Synapse.cpp.o
[ 94%] Building CXX object synapse/CMakeFiles/synapse.dir/SeqSynHandler.cpp.o
In file included from /home/bhalla/moose/moose-core/synapse/../external/muparser/include/muParserStack.h:35:0,
                 from /home/bhalla/moose/moose-core/synapse/../external/muparser/include/muParserBase.h:39,
                 from /home/bhalla/moose/moose-core/synapse/../external/muparser/include/muParser.h:32,
                 from /home/bhalla/moose/moose-core/synapse/SeqSynHandler.cpp:17:
/home/bhalla/moose/moose-core/synapse/../external/muparser/include/muParserToken.h:72:12: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
       std::auto_ptr<ParserCallback> m_pCallback;
            ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/bhalla/moose/moose-core/synapse/../external/muparser/include/muParserBase.h:33,
                 from /home/bhalla/moose/moose-core/synapse/../external/muparser/include/muParser.h:32,
                 from /home/bhalla/moose/moose-core/synapse/SeqSynHandler.cpp:17:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /home/bhalla/moose/moose-core/synapse/../external/muparser/include/muParser.h:32:0,
                 from /home/bhalla/moose/moose-core/synapse/SeqSynHandler.cpp:17:
/home/bhalla/moose/moose-core/synapse/../external/muparser/include/muParserBase.h:291:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<token_reader_type> m_pTokenReader; ///< Managed pointer to the token reader object.
          ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/bhalla/moose/moose-core/synapse/../external/muparser/include/muParserBase.h:33,
                 from /home/bhalla/moose/moose-core/synapse/../external/muparser/include/muParser.h:32,
                 from /home/bhalla/moose/moose-core/synapse/SeqSynHandler.cpp:17:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
[ 94%] Linking CXX static library libsynapse.a
[ 94%] Built target synapse
Scanning dependencies of target libmoose
[ 94%] Building CXX object CMakeFiles/libmoose.dir/basecode/main.cpp.o
[ 95%] Linking CXX shared library libmoose.so
builtins/libmoose_builtins.a(testNSDF.cpp.o): In function `testCreateStringDataset()':
testNSDF.cpp:(.text+0x6b): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
[ 95%] Built target libmoose
Scanning dependencies of target moose.bin
[ 95%] Building CXX object CMakeFiles/moose.bin.dir/basecode/main.cpp.o
[ 96%] Linking CXX executable moose.bin
[ 96%] Built target moose.bin
Scanning dependencies of target copy_python_files
[ 97%] Copying required python files and other files to build directory
[ 97%] Built target copy_python_files
Scanning dependencies of target _moose
[ 97%] Building CXX object pymoose/CMakeFiles/_moose.dir/moosemodule.cpp.o
[ 97%] Building CXX object pymoose/CMakeFiles/_moose.dir/vec.cpp.o
[ 98%] Building CXX object pymoose/CMakeFiles/_moose.dir/mfield.cpp.o
[ 98%] Building CXX object pymoose/CMakeFiles/_moose.dir/pymooseinit.cpp.o
[ 99%] Building CXX object pymoose/CMakeFiles/_moose.dir/melement.cpp.o
[ 99%] Building CXX object pymoose/CMakeFiles/_moose.dir/test_moosemodule.cpp.o
[ 99%] Building CXX object pymoose/CMakeFiles/_moose.dir/PyRun.cpp.o
[100%] Linking CXX shared module ../python/moose/_moose.so
../builtins/libmoose_builtins.a(testNSDF.cpp.o): In function `testCreateStringDataset()':
testNSDF.cpp:(.text+0x6b): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
[100%] Built target _moose
+ ctest -output-on-failure
Test project /home/bhalla/moose/__moose-core_build
      Start  1: moose.bin-raw-run
 1/13 Test  #1: moose.bin-raw-run ..................   Passed    0.02 sec
      Start  2: pymoose-test-synchan
 2/13 Test  #2: pymoose-test-synchan ...............***Failed    0.01 sec
      Start  3: pymoose-test-function
 3/13 Test  #3: pymoose-test-function ..............***Failed    0.10 sec
      Start  4: pymoose-test-vec
 4/13 Test  #4: pymoose-test-vec ...................***Failed    0.01 sec
      Start  5: pymoose-pyrun
 5/13 Test  #5: pymoose-pyrun ......................***Failed    0.01 sec
      Start  6: pymoose-neuroml-reader-test
 6/13 Test  #6: pymoose-neuroml-reader-test ........***Failed    0.01 sec
      Start  7: pymoose-nsdf-sanity-test
 7/13 Test  #7: pymoose-nsdf-sanity-test ...........***Failed    0.14 sec
      Start  8: pymoose-ksolve-test
 8/13 Test  #8: pymoose-ksolve-test ................***Failed    0.11 sec
      Start  9: pymoose-test-basic-sbml-support
 9/13 Test  #9: pymoose-test-basic-sbml-support ....***Failed    0.01 sec
      Start 10: pymoose-test-rng
10/13 Test #10: pymoose-test-rng ...................***Failed    0.04 sec
      Start 11: pymoose-test-streamer
11/13 Test #11: pymoose-test-streamer ..............***Failed    0.01 sec
      Start 12: pymoose-test-streaming_in_tables
12/13 Test #12: pymoose-test-streaming_in_tables ...***Failed    0.01 sec
      Start 13: pymoose-test-kkit
13/13 Test #13: pymoose-test-kkit ..................***Failed    0.37 sec

8% tests passed, 12 tests failed out of 13

Total Test time (real) =   0.85 sec

The following tests FAILED:
	  2 - pymoose-test-synchan (Failed)
	  3 - pymoose-test-function (Failed)
	  4 - pymoose-test-vec (Failed)
	  5 - pymoose-pyrun (Failed)
	  6 - pymoose-neuroml-reader-test (Failed)
	  7 - pymoose-nsdf-sanity-test (Failed)
	  8 - pymoose-ksolve-test (Failed)
	  9 - pymoose-test-basic-sbml-support (Failed)
	 10 - pymoose-test-rng (Failed)
	 11 - pymoose-test-streamer (Failed)
	 12 - pymoose-test-streaming_in_tables (Failed)
	 13 - pymoose-test-kkit (Failed)
Errors while running CTest
+ echo 'Some tests failed'
Some tests failed
+ make install
[  4%] Built target intfire
[ 14%] Built target basecode
[ 18%] Built target msg
[ 22%] Built target shell
[ 28%] Built target randnum
[ 29%] Built target scheduling
[ 46%] Built target biophysics
[ 55%] Built target moose_builtins
[ 59%] Built target utility
[ 64%] Built target mesh
[ 65%] Built target moose_mpi
[ 66%] Built target signeur
[ 74%] Built target ksolve
[ 79%] Built target hsolve
[ 81%] Built target diffusion
[ 83%] Built target device
[ 84%] Built target benchmarks
[ 90%] Built target kinetics
[ 94%] Built target synapse
[ 95%] Built target libmoose
[ 96%] Built target moose.bin
[ 97%] Copying required python files and other files to build directory
[ 97%] Built target copy_python_files
[100%] Built target _moose
Install the project...
-- Install configuration: "Release"
-- Installing: /home/bhalla/moose/__moose-core_install/bin/moose.bin
-- Set runtime path of "/home/bhalla/moose/__moose-core_install/bin/moose.bin" to ""
-- Installing: /home/bhalla/moose/__moose-core_install/lib/libmoose.so
-- Set runtime path of "/home/bhalla/moose/__moose-core_install/lib/libmoose.so" to ""
-- Installing: /home/bhalla/moose/__moose-core_install/bin/moose
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/rdesigneur

Please suggest.

Thanks,
Chakrapani

**Comment by dilawar** [comment]
I am failing to reproduce this on 16.04 also. Can you post the `__moose-core_build/CMakeCache.txt` file. It must be in the same folder where you building.

**Comment by ChakrapaniNCBS** [comment]
File attached.
[CMakeCache.txt](https://github.com/BhallaLab/moose/files/975550/CMakeCache.txt)
Also there is no error during cmake.  file is attached 
[moose-cmake.txt](https://github.com/BhallaLab/moose/files/975560/moose-cmake.txt)

Thanks

**Comment by dilawar** [comment]
I think this has been fixed.
