### ISSUE TITLE
`hidden_code_block` support in pdf and epub

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose#232]
While `hidden_code_block` working great (PR #225) with HTML docs, it is not properly configured for pdf (and possibly) epub. Commit https://github.com/BhallaLab/moose/commit/22eb3d1a995d8e8024699b685d31ba42532985f6 fixes build issue by simply writing a visitor for this type of node. This node needs to class Latex code class node. 

- [x] Update credit
- [x] Convert `gif` to `jpeg` or `png`.

**Comment by dilawar** [comment]
@Dhruva-Storz Are `gif` required in html documentation?

In `PDF` they wont be visible by default. If they can be replaced by `png`; I'd replace them with PNG. If they are required for showing animation; I'll think of something else.

**Comment by Dhruva-Storz** [comment]
They are required to show what happens at each time step of the simulation.

**Comment by dilawar** [comment]
Ok. PDF just shows the first frame of gif animation.
