### ISSUE TITLE
Starting moose in docker with moosegui

### ISSUE THREAD

**Issue by lungsi** [BhallaLab/moose#245]
I have been unsuccessful to start `moosegui` in docker. I have followed
`$ docker run -it --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY bhallalab/moose`

`xterm` is not launched to run `moosegui` in terminal. Since it is not automatically launched I open a terminal manually and run `moosegui` which results in
`bash: moosegui: command not found...`

My environment is Fedora28 and 
`$ ls /tmp/.X11-unix`
`X0 X1024`

**Comment by dilawar** [comment]
That's embarassing. I'll have a look in the morning.

Cheers,
    Dilawar 

On 30 October 2018 7:00:39 PM IST, lungsi <notifications@github.com> wrote:
>I have been unsuccessful to start `moosegui` in docker. I have followed
>`$ docker run -it --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e
>DISPLAY=$DISPLAY bhallalab/moose`
>
>`xterm` is not launched to run `moosegui` in terminal. Since it is not
>automatically launched I open a terminal manually and run `moosegui`
>which results in
>`bash: moosegui: command not found...`
>
>My environment is Fedora28 and 
>`$ ls /tmp/.X11-unix`
>`X0 X1024`
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/BhallaLab/moose/issues/245

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dilawar** [comment]
Hi @lungsi .  

I have updated the docker image  with dependencies installed. I have tested it with an Ubuntu host. The script I used for testing is following:

```
docker run -ti --rm -e DISPLAY=:0 -v /tmp/.X11-unix:/tmp/.X11-unix bhallalab/moose:latest
```

Please pull the latest image.

**Comment by lungsi** [comment]
Thanks so much @dilawar 
I confirm that I successfully launched `moosegui` in the `xterm` pop-up.

PS: I deleted the image and re-pulled the latest docker image.
