### ISSUE TITLE
Setting CaConc Ca_base in redesigneur ChanDistrib

### ISSUE THREAD

**Issue by analkumar2** [BhallaLab/moose#261]
Not able to change CaBasal or Ca_base value using rdesigneur's ChanDistrib field.
Attached are three files:

- CheckCaconcbasal.py -- Builds the model and inject current  into the model

- Ca_N_Chan_(Migliore2018).py -- The channel kinetics file. The channel is dependent on calcium and also is a input field to the calcium decay mechanism

- Ca_Conc_(Common).py -- calcium decay mechanism. tau is default to 100e-3s. Ca_base is default to 0.05e-3mM.

In the code, when we use ChanDistribto change the value of Ca_base to 0.1e-3mM and tau to 50e-3s, 
chanDistrib = [['Ca_N_chan', 'soma', 'Gbar', '1'], ['Ca_conc', 'soma', 'Ca_base', str(0.1e-3), 'tau', '50e-3']]

The tau gets changed to 50e-3s, but Ca_base or CaBasal remains to their default values. The only way to change Ca_base is to modify the calcium decay mechanism file.

[CheckCaconcbasal.txt](https://github.com/BhallaLab/moose/files/3542575/CheckCaconcbasal.txt)
[Ca_Conc_(Common).txt](https://github.com/BhallaLab/moose/files/3542576/Ca_Conc_.Common.txt)
[Ca_N_Chan_(Migliore2018).txt](https://github.com/BhallaLab/moose/files/3542577/Ca_N_Chan_.Migliore2018.txt)

**Comment by analkumar2** [comment]
Resolved
Before running a new model, the Ca_Conc in the library has to be deleted using moose.delete('/library/Ca_conc') in addition to deleting the previous model using moose.delete('/model'). If just the model is deleted, the CaBasal cannot be modified using ChanDistrib.

**Comment by dilawar** [comment]
Its bit odd. The library should be readonly. Desired elements from library should be copied into model using `moose.copy`. When you prepare document, you can add a note/warning.

**Comment by analkumar2** [comment]
I am using Rdesigneur to set up the library and the model. Rdesigneur takes care of copying the elements from the library to model.
