### ISSUE TITLE
Failing to import moose in python

### ISSUE THREAD

**Issue by angiechamberland** [BhallaLab/moose#263]
I keep getting this error message when trying to import moose in python - anyone have any ideas?

>>> import moose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/angiechamberland/.local/lib/python3.7/site-packages/moose/__init__.py", line 10, in <module>
    from moose._moose import *
ImportError: dlopen(/Users/angiechamberland/.local/lib/python3.7/site-packages/moose/_moose.so, 2): no suitable image found.  Did find:
	/Users/angiechamberland/.local/lib/python3.7/site-packages/moose/_moose.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
	/Users/angiechamberland/.local/lib/python3.7/site-packages/moose/_moose.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03

**Comment by dilawar** [comment]
This is discussed https://github.com/BhallaLab/homebrew-moose/issues/1
