### ISSUE TITLE
Combining axon and dendrite models in Rdesigneur 

### ISSUE THREAD

**Issue by ishanseth18** [BhallaLab/moose#270]
Hi, I am having some trouble getting both the dendrites and the axons in one model using rdesignuer. Currently, I am trying to use the following line to combine the separate models:

cellProto = [['ballAndStick', 'soma', 20e-6, 20e-6, 4e-6, 500e-6, 10],
                ['elec','axon']
                ],

However, this gives me the result of showing either the dendrite model or the axon model, which is not what I want. 

Given that only one model runs at a time with the code I am currently running, am I correct in thinking that only one 'cellProto' can be run at a time?

More importantly, how can I get.a model working that has both the dendrites and the axons involved?

Thanks so much.

**Comment by dilawar** [comment]
@upibhalla This needs your input.

**Comment by hrani** [comment]
Hi,
Heard from Upi that this can be doable. He will get back as soon as
possible.

**Comment by ishanseth18** [comment]
Thank you so much!

**Comment by ishanseth18** [comment]
I am looking at the moose examples you have on the guthub and it seems to me that all of these only use one Prototype for  "cellProto". If both cannot be modeled at the same time, how would you suggest I go about modeling a complete neuron, with axon, soma, and dendrite? My end goal would be to model a simple neural network.

Thank you for your help.

**Comment by hrani** [comment]
Hi,
This is Upi's reply
"That one can already have all these regions in the cellProto. The built in
ones are soma and dendrite, but one can load from SWC etc and if there is a
strong need one could add another default prototype that has all the three
regions."

we also suggest to look into ex9.0 rdesignuer example.
Hope this helps
