### ISSUE TITLE
ex8.0_multiscale_KA_phosph.py rdesigneur example error

### ISSUE THREAD

**Issue by ishanseth18** [BhallaLab/moose#271]
Currently I am getting an error running ex8.0_multiscale_KA_phosph.py on the rdesignuer documentation but I am confused as to why. I'm getting the following message:

Traceback (most recent call last):
  File "/Users/ishanseth/Desktop/Personal/Research/CalChan.py", line 4, in <module>
    rdes = rd.rdesigneur(
  File "/Users/ishanseth/Desktop/Personal/Research/venv/lib/python3.8/site-packages/rdesigneur/rdesigneur.py", line 186, in __init__
    self.buildChemProto()
  File "/Users/ishanseth/Desktop/Personal/Research/venv/lib/python3.8/site-packages/rdesigneur/rdesigneur.py", line 444, in buildChemProto
    self._loadChem( i[0], i[1] )
  File "/Users/ishanseth/Desktop/Personal/Research/venv/lib/python3.8/site-packages/rdesigneur/rdesigneur.py", line 1424, in _loadChem
    modelId = moose.loadModel( fname, chem.path, 'ee' )
  File "/Users/ishanseth/Desktop/Personal/Research/venv/lib/python3.8/site-packages/moose/__init__.py", line 478, in loadModel
    return model_utils.mooseReadKkitGenesis(filename, modelpath, solverclass)
  File "/Users/ishanseth/Desktop/Personal/Research/venv/lib/python3.8/site-packages/moose/model_utils.py", line 158, in mooseReadKkitGenesis
    raise FileNotFoundError("Model file '%s' found." % filename)
FileNotFoundError: Model file './chem/chanPhosphByCaMKII.g' found.

Anyway I can fix this? Thank you so much.

**Comment by dilawar** [comment]
I suspect this file should be in this folder https://github.com/BhallaLab/moose-core/tree/master/python/rdesigneur/chans but missing. I could not find this file everywhere on github. Potentially a missing file.

Try creating a dummy file with no content in this directory and see if this is true.

**Comment by dilawar** [comment]
Found it. Download it from here and keep in the `chem` folder (in the same directory where you running this file). https://github.com/BhallaLab/moose-examples/tree/master/tutorials/Rdesigneur/chem

**Comment by ishanseth18** [comment]
Thanks so much! I see the link but I do not see the green button I need to download the code. I tried a git pull request with the url of the link above but it says the repository is not found. Sorry, I am still a little new to GitHub and am not totally comfortable using it. How should I go about downloading?

**Comment by dilawar** [comment]
Two ways:


1. Use `git clone https://github.com/BhallaLab/moose-examples` to clone the whole repo and copy the file you need. This is the simplest method. 
2. In directory shown by url I posted before, Click on filen you want to download. Then click on `Download` or `Raw` button. You will get a text file in the browser. Use Ctrl+s or `Save File` in file menu to save this file. 

There is a complicated way to clone only a subdirectory. I'd suggest clone the whole repo and use the files you need.  

⁣Sent from a handheld device, please pardon my brevity and tpyos. 

Get BlueMail for Android ​

**Comment by ishanseth18** [comment]
I tried the clone just now and I am still getting the same error. However, I do see the file on my computer. Is there another reason why I may be getting this error?

**Comment by dilawar** [comment]
You have to make sure that you run the script from it's directory. Note
that the .g model being loaded has its path that is relative to the
directory of the python script.

Post the terminal output as well.

**Comment by ishanseth18** [comment]
It seems that the file is in the correct location. I see It at ./moose-gui/tutorials/Rdesignuer/chem/ This matches with the output I posted above (same error I am getting now): 

Traceback (most recent call last):
  File "/Users/ishanseth/Desktop/Personal/Research/CalChan.py", line 4, in <module>
    rdes = rd.rdesigneur(
  File "/Users/ishanseth/Desktop/Personal/Research/venv/lib/python3.8/site-packages/rdesigneur/rdesigneur.py", line 186, in __init__
    self.buildChemProto()
  File "/Users/ishanseth/Desktop/Personal/Research/venv/lib/python3.8/site-packages/rdesigneur/rdesigneur.py", line 444, in buildChemProto
    self._loadChem( i[0], i[1] )
  File "/Users/ishanseth/Desktop/Personal/Research/venv/lib/python3.8/site-packages/rdesigneur/rdesigneur.py", line 1424, in _loadChem
    modelId = moose.loadModel( fname, chem.path, 'ee' )
  File "/Users/ishanseth/Desktop/Personal/Research/venv/lib/python3.8/site-packages/moose/__init__.py", line 478, in loadModel
    return model_utils.mooseReadKkitGenesis(filename, modelpath, solverclass)
  File "/Users/ishanseth/Desktop/Personal/Research/venv/lib/python3.8/site-packages/moose/model_utils.py", line 158, in mooseReadKkitGenesis
    raise FileNotFoundError("Model file '%s' found." % filename)
FileNotFoundError: Model file './chem/chanPhosphByCaMKII.g' found.

**Comment by dilawar** [comment]
Just to confirm, you top-level script is in `./moose-gui/tutorials/Rdesignuer/` folder?  This should be your directory structure.

```
├── cells
│   ├── barrionuevo_cell1zr.CNG.swc
│   └── h10.CNG.swc
├── chans
│   ├── CA1.morph.spines.xml
│   ├── CA1_nochans.morph.xml
│   ├── CA1spiny7_0.morph.xml
│   ├── CA1spiny.morph.xml
│   ├── Ca_conc.xml
│   ├── CaConc.xml
│   ├── Ca.xml
│   ├── GABA.xml
│   ├── Glu.xml
│   ├── hd.xml
│   ├── kad.xml
│   ├── kap.xml
│   ├── kdr.xml
│   ├── na3.xml
│   ├── nax.xml
│   ├── NMDA.xml
│   └── proto22.py
├── chem
│   ├── chanPhosph3compt.g
│   ├── chanPhosphByCaMKII.g
│   ├── CICRspineDend.g
│   ├── CICRwithConcChan.g
├── ex8.0_multiscale_KA_phosph.py
```

**Comment by hrani** [comment]
ishanseth18
git clone https://github.com/BhallaLab/moose-examples.git  moose-examples
if you clone like this and cd to moose-examples/tutorials/Rdesigneur
python ex8.0_multiscale_KA_phosph.py it should run without any error as the
file is with same folder
(moose-examples/tutorial/Rdesigneur/chem/chanPhosphByCaMKII.g)
I just tested this now and its working, if you done the same instead of
moose-examples if you have save in moose-gui folder then it still work..
if you still have the same problem we would suggest you clone to a separate
folder and try

**Comment by ishanseth18** [comment]
Yes, I just confirmed that that is my directory structure. I see all of those files in the given folders.

**Comment by ishanseth18** [comment]
Thank you so much, I will try that and let you know.
