### ISSUE TITLE
Make failed for revision 6765

### ISSUE THREAD

**Issue by iampritishpatil** [BhallaLab/moose#4]
after svn update to revision 6765, and make clean,

 make USE_SBML=1

Failed. It gave the following error:

g++ -O3 -fpermissive -fno-strict-aliasing -fPIC -Wall -Wno-long-long -pedantic -DNDEBUG -DUSE_GENESIS_PARSER -DSVN_REVISION=\"6765M\" -DLINUX -DUSE_GSL -DUSE_SBML -DUSE_NUMPY -DUSE_HDF5  -DH5_NO_DEPRECATED_SYMBOLS -I/usr/local/hdf5/include  -I. -I../basecode -I../msg DifShell.cpp -c
DifShell.cpp:13:21: fatal error: numutil.h: No such file or directory
 #include "numutil.h"
                     ^
compilation terminated.
make[1]: *** [DifShell.o] Error 1
make[1]: Leaving directory `/data/College/Summer 2015/MOOSE/june1/moose/biophysics'
make: *** [libs] Error 2

**Comment by dilawar** [comment]
Fixed this in latest commit. Though the trunk is bit unstable. I am testing it
on Windows and python2 and python3.

**Comment by dilawar** [comment]
Passed on travis using cmake.
