### ISSUE TITLE
"step" oversteps

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose#51]
If "step" is issued without arguments, the scheduler advances time by either 1 or 2 steps.

Can't think of a simple script to reproduce this problem \("getstat" is not working\).

This problem was discovered in a script that looked like this:

for \( i = 0; i &lt; 3000; i = i + 1 \)
step
end

A plot object was connected to a compartment, and stored around 4500 points in the output file. In particular, the very first call of "step" steps twice. Subsequently, the system alternates between behaving and misbehaving according to some pattern \(did not investigate\).

Should also check if "step" behaves well for all integer arguments.

Reported by: niraj_

**Comment by dilawar** [comment]
Too old. Probably fixed long time back.
