### ISSUE TITLE
Class get functions dont work

### ISSUE THREAD

**Issue by iampritishpatil** [BhallaLab/moose#9]
example where 
model_elec=moose.element(rdes.model.path+"/elec")

In [25]: model_elec.getPathDistanceFromSoma()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-25-663d29f02b49> in <module>()
----> 1 model_elec.getPathDistanceFromSoma()

TypeError: moose.setDestField: Arguments not handled: getPathDistanceFromSoma(PSt6vectorIS_IdSaIdEESaIS1_EE,)

Many such functions are not working.

**Comment by dilawar** [comment]
According to Subha,

Get functions were not designed to be used that way. They are destfinfos which are mostly used internally in moose. But they are exposed as object methods in pymoose as it was felt that the ones with simple arguments should be callable in user script. The exception tells you exactly what is the problem:

The function expects a vector of Ids as argument and that case is not handled by pymoose.
